name = "SemioticTransformer"
uuid = "0b70ca6e-b118-4a76-bdfe-df6c6714c5c2"
authors = ["Ryo âˆ´ SpiralArchitect <kishkavsesvit@icloud.com>"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-91d6-54ec-9ede-0928a1b6a27f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Random = "9a3f8284-393e-5b7d-84e7-a7ef1b0ebc6f"


[compat]
julia = "1.6, 1.7, 1.8, 1.9, 1.10, 1.12"
Flux = "0.14, 0.15, 0.16"
Functors = "0.4, 0.5"
NNlib = "^0.9"
