name = "SemioticTransformer"
uuid = "0b70ca6e-b118-4a76-bdfe-df6c6714c5c2"
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Functors = "d9f16b24-f501-4c13-a1f2-7e19794d3f1f"

[compat]
julia = "1.9"
Flux = "0.14"
NNlib = "0.9"
Functors = "0.4"
